CREATE TABLE COMMENT_VOTES(
USER_ID             INTEGER REFERENCES USER(USER_ID),
COMMENT_ID          INTEGER REFERENCES COMMENT(COMMENT_ID),
STATE               INTEGER,
TIMESTAMPS          TIMESTAMP NOT NULL
);