CREATE TABLE COMMENT(
COMMENT_ID  INTEGER PRIMARY KEY,
PARENT_ID   INTEGER,
MESSAGE     TEXT,
USER_ID     INTEGER REFERENCES USER(USER_ID),
POST_ID     INTEGER REFERENCES POST(POST_ID),
LINK_ID     INTEGER,
TIMESTAMPS  TIMESTAMP
);