CREATE TABLE POSTS(
TITLE               TEXT,
CONTENT_MD          TEXT,
CONTENT_HTML        TEXT,
DRAFT               BOOLEAN DEFAULT FALSE,
USER_ID             INTEGER REFERENCES USER(USER_ID),
FIRST_NAME          TEXT,
LAST_NAME           TEXT,
FULL_NAME           TEXT,
SLUG,
YEAR_CREATED        INTEGER,
MEDIUM              TEXT,
DIMENSION_HEIGHT    INTEGER,
DIMENSION_WIDTH     INTEGER,
MEASUREMENT         TEXT,
WEIGHT_IN_POUNDS    INTEGER,
PRICE               INTEGER,
QUANTITY            INTEGER,
SLUG                TEXT,
TIMESTAMPS          TIMESTAMP,
);
CREATE INDEX POST_INDEX 
USER_ID ON POSTS(USER_ID);